// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Generate
{
    /// <summary>One of `GENERATION|NONE` to specify how and if the token likelihoods are returned with the response. Defaults to `NONE`.If `GENERATION` is selected, the token likelihoods will only be provided for generated text.WARNING: `ALL` is deprecated, and will be removed in a future release.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GeneratePostRequestBody_return_likelihoods
    {
        [EnumMember(Value = "GENERATION")]
        #pragma warning disable CS1591
        GENERATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        ALL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
    }
}
