// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.V2.Audio.Transcriptions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Audio
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\audio
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AudioRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The transcriptions property</summary>
        public global::Soenneker.Cohere.OpenApiClient.V2.Audio.Transcriptions.TranscriptionsRequestBuilder Transcriptions
        {
            get => new global::Soenneker.Cohere.OpenApiClient.V2.Audio.Transcriptions.TranscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Audio.AudioRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudioRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/audio", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Audio.AudioRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AudioRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/audio", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
