// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiMeta : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The api_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_api_version? ApiVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_api_version ApiVersion { get; set; }
#endif
        /// <summary>The billed_units property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_billed_units? BilledUnits { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_billed_units BilledUnits { get; set; }
#endif
        /// <summary>The number of prompt tokens that hit the inference cache.</summary>
        public double? CachedTokens { get; set; }
        /// <summary>The tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_tokens? Tokens { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_tokens Tokens { get; set; }
#endif
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Warnings { get; set; }
#nullable restore
#else
        public List<string> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta"/> and sets the default values.
        /// </summary>
        public ApiMeta()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_version", n => { ApiVersion = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_api_version>(global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_api_version.CreateFromDiscriminatorValue); } },
                { "billed_units", n => { BilledUnits = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_billed_units>(global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_billed_units.CreateFromDiscriminatorValue); } },
                { "cached_tokens", n => { CachedTokens = n.GetDoubleValue(); } },
                { "tokens", n => { Tokens = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_tokens>(global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_tokens.CreateFromDiscriminatorValue); } },
                { "warnings", n => { Warnings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_api_version>("api_version", ApiVersion);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_billed_units>("billed_units", BilledUnits);
            writer.WriteDoubleValue("cached_tokens", CachedTokens);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta_tokens>("tokens", Tokens);
            writer.WriteCollectionOfPrimitiveValues<string>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
