// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// A message from the assistant role can contain text and tool call information.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssistantMessageV2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The citations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Citation>? Citations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Citation> Citations { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content? Content { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content Content { get; set; }
#endif
        /// <summary>The role property</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2_role? Role { get; set; }
        /// <summary>The tool_calls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolCallV2>? ToolCalls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolCallV2> ToolCalls { get; set; }
#endif
        /// <summary>A chain-of-thought style reflection and plan that the model generates when working with Tools.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolPlan { get; set; }
#nullable restore
#else
        public string ToolPlan { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2"/> and sets the default values.
        /// </summary>
        public AssistantMessageV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "citations", n => { Citations = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Citation>(global::Soenneker.Cohere.OpenApiClient.Models.Citation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content>(global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content.CreateFromDiscriminatorValue); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2_role>(); } },
                { "tool_calls", n => { ToolCalls = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolCallV2>(global::Soenneker.Cohere.OpenApiClient.Models.ToolCallV2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tool_plan", n => { ToolPlan = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Citation>("citations", Citations);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content>("content", Content);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2_role>("role", Role);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolCallV2>("tool_calls", ToolCalls);
            writer.WriteStringValue("tool_plan", ToolPlan);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AssistantMessageV2_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent>? ChatThinkingContent { get; set; }
#nullable restore
#else
            public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent> ChatThinkingContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageV2.AssistantMessageV2_content();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent>(global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent> chatThinkingContentValue)
                {
                    result.ChatThinkingContent = chatThinkingContentValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else if(ChatThinkingContent != null)
                {
                    writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatThinkingContent>(null, ChatThinkingContent);
                }
            }
        }
    }
}
#pragma warning restore CS0618
