// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>&quot;The possible stages of a batch life-cycle. - BATCH_STATUS_UNSPECIFIED: Unspecified status. - BATCH_STATUS_QUEUED: The batch has been queued. - BATCH_STATUS_IN_PROGRESS: The batch is in-progress. - BATCH_STATUS_CANCELING: The batch is being canceled. - BATCH_STATUS_COMPLETED: The batch has been completed. - BATCH_STATUS_FAILED: The batch has failed. - BATCH_STATUS_CANCELED: The batch has been canceled.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchStatus
    {
        [EnumMember(Value = "BATCH_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        BatchStatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_QUEUED")]
        #pragma warning disable CS1591
        BatchStatusQueued,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_IN_PROGRESS")]
        #pragma warning disable CS1591
        BatchStatusInProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_CANCELING")]
        #pragma warning disable CS1591
        BatchStatusCanceling,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_COMPLETED")]
        #pragma warning disable CS1591
        BatchStatusCompleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_FAILED")]
        #pragma warning disable CS1591
        BatchStatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_CANCELED")]
        #pragma warning disable CS1591
        BatchStatusCanceled,
        #pragma warning restore CS1591
    }
}
