// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// This resource represents a batch job.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Batch : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>read-only. Creation timestamp.</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>read-only. User ID of the creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; private set; }
#nullable restore
#else
        public string CreatorId { get; private set; }
#endif
        /// <summary>read-only. Batch ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>ID of the dataset the batch reads inputs from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputDatasetId { get; set; }
#nullable restore
#else
        public string InputDatasetId { get; set; }
#endif
        /// <summary>read-only. The total number of input tokens in the batch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputTokens { get; private set; }
#nullable restore
#else
        public string InputTokens { get; private set; }
#endif
        /// <summary>The name of the model the batch uses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Batch name (e.g. `foobar`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>read-only. The current number of failed records in the batch.</summary>
        public int? NumFailedRecords { get; private set; }
        /// <summary>read-only. The total number of records in the batch.</summary>
        public int? NumRecords { get; private set; }
        /// <summary>read-only. The current number of successful records in the batch.</summary>
        public int? NumSuccessfulRecords { get; private set; }
        /// <summary>read-only. Organization ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; private set; }
#nullable restore
#else
        public string OrgId { get; private set; }
#endif
        /// <summary>The output_dataset_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputDatasetId { get; private set; }
#nullable restore
#else
        public string OutputDatasetId { get; private set; }
#endif
        /// <summary>read-only. The total number of output tokens in the batch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputTokens { get; private set; }
#nullable restore
#else
        public string OutputTokens { get; private set; }
#endif
        /// <summary>read-only. Current stage in the life-cycle of the batch.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.BatchStatus? Status { get; private set; }
        /// <summary>read-only. More details about the reason for the status of a batch job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; private set; }
#nullable restore
#else
        public string StatusReason { get; private set; }
#endif
        /// <summary>read-only. Latest update timestamp.</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Batch"/> and sets the default values.
        /// </summary>
        public Batch()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Cohere.OpenApiClient.Models.BatchStatus.BATCH_STATUS_UNSPECIFIED;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Batch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.Batch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.Batch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input_dataset_id", n => { InputDatasetId = n.GetStringValue(); } },
                { "input_tokens", n => { InputTokens = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "num_failed_records", n => { NumFailedRecords = n.GetIntValue(); } },
                { "num_records", n => { NumRecords = n.GetIntValue(); } },
                { "num_successful_records", n => { NumSuccessfulRecords = n.GetIntValue(); } },
                { "org_id", n => { OrgId = n.GetStringValue(); } },
                { "output_dataset_id", n => { OutputDatasetId = n.GetStringValue(); } },
                { "output_tokens", n => { OutputTokens = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.BatchStatus>(); } },
                { "status_reason", n => { StatusReason = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("input_dataset_id", InputDatasetId);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
