// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>read-only. Current stage in the life-cycle of the batch.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchStatus
    {
        [EnumMember(Value = "BATCH_STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        BATCH_STATUS_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_QUEUED")]
        #pragma warning disable CS1591
        BATCH_STATUS_QUEUED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_IN_PROGRESS")]
        #pragma warning disable CS1591
        BATCH_STATUS_IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_CANCELING")]
        #pragma warning disable CS1591
        BATCH_STATUS_CANCELING,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_COMPLETED")]
        #pragma warning disable CS1591
        BATCH_STATUS_COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_FAILED")]
        #pragma warning disable CS1591
        BATCH_STATUS_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "BATCH_STATUS_CANCELED")]
        #pragma warning disable CS1591
        BATCH_STATUS_CANCELED,
        #pragma warning restore CS1591
    }
}
