// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1"/>, <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Document"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Chatv2RequestDocumentsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1? Chatv2RequestDocumentsItemBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1 Chatv2RequestDocumentsItemBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Document"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Document? Document { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Document Document { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItem();
            if("Chatv2RequestDocumentsItemBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Chatv2RequestDocumentsItemBranch1 = new global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1();
            }
            else if("Document".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Document = new global::Soenneker.Cohere.OpenApiClient.Models.Document();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Chatv2RequestDocumentsItemBranch1 != null)
            {
                return Chatv2RequestDocumentsItemBranch1.GetFieldDeserializers();
            }
            else if(Document != null)
            {
                return Document.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Chatv2RequestDocumentsItemBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Chatv2RequestDocumentsItemBranch1>(null, Chatv2RequestDocumentsItemBranch1);
            }
            else if(Document != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Document>(null, Document);
            }
        }
    }
}
#pragma warning restore CS0618
