// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>One of `CHATBOT`, `SYSTEM`, `TOOL` or `USER` to identify who the message is coming from.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatRole
    {
        [EnumMember(Value = "CHATBOT")]
        #pragma warning disable CS1591
        Chatbot,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOOL")]
        #pragma warning disable CS1591
        Tool,
        #pragma warning restore CS1591
    }
}
