// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatResponseV2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The reason a chat request has finished.- **complete**: The model finished sending a complete message.- **max_tokens**: The number of generated tokens exceeded the model&apos;s context length or the value specified via the `max_tokens` parameter.- **stop_sequence**: One of the provided `stop_sequence` entries was reached in the model&apos;s generation.- **tool_call**: The model generated a Tool Call and is expecting a Tool Message in return- **error**: The generation failed due to an internal error- **timeout**: The generation was stopped because it exceeded the allowed time limit.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatFinishReason? FinishReason { get; set; }
        /// <summary>Unique identifier for the generated reply. Useful for submitting feedback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The logprobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.LogprobItem>? Logprobs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.LogprobItem> Logprobs { get; set; }
#endif
        /// <summary>A message from the assistant role can contain text and tool call information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageResponse? Message { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageResponse Message { get; set; }
#endif
        /// <summary>The usage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Usage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Usage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2"/> and sets the default values.
        /// </summary>
        public ChatResponseV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "finish_reason", n => { FinishReason = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatFinishReason>(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "logprobs", n => { Logprobs = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.LogprobItem>(global::Soenneker.Cohere.OpenApiClient.Models.LogprobItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "message", n => { Message = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageResponse>(global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageResponse.CreateFromDiscriminatorValue); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Usage>(global::Soenneker.Cohere.OpenApiClient.Models.Usage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatFinishReason>("finish_reason", FinishReason);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.LogprobItem>("logprobs", Logprobs);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.AssistantMessageResponse>("message", Message);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Usage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
