// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>&quot;Defaults to `\&quot;enabled\&quot;`.Citations are enabled by default for models that support it, but can be turned off by setting `\&quot;type\&quot;: \&quot;disabled\&quot;`.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatRequestCitationQuality
    {
        [EnumMember(Value = "ENABLED")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLED")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAST")]
        #pragma warning disable CS1591
        Fast,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCURATE")]
        #pragma warning disable CS1591
        Accurate,
        #pragma warning restore CS1591
        [EnumMember(Value = "OFF")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
    }
}
