// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatThinkingContent_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "thinking")]
        #pragma warning disable CS1591
        Thinking,
        #pragma warning restore CS1591
    }
}
