// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>The role of the message.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatMessageStartEventAllOf2DeltaMessageRole
    {
        [EnumMember(Value = "assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
    }
}
