// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatSearchResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The connector from which this result comes from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResultConnector? Connector { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResultConnector Connector { get; set; }
#endif
        /// <summary>Whether a chat request should continue or not if the request to this connector fails.</summary>
        public bool? ContinueOnFailure { get; set; }
        /// <summary>Identifiers of documents found by this search query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DocumentIds { get; set; }
#nullable restore
#else
        public List<string> DocumentIds { get; set; }
#endif
        /// <summary>An error message if the search failed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The generated search query. Contains the text of the query and a unique identifier for the query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery? SearchQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery SearchQuery { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult"/> and sets the default values.
        /// </summary>
        public ChatSearchResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connector", n => { Connector = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResultConnector>(global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResultConnector.CreateFromDiscriminatorValue); } },
                { "continue_on_failure", n => { ContinueOnFailure = n.GetBoolValue(); } },
                { "document_ids", n => { DocumentIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "error_message", n => { ErrorMessage = n.GetStringValue(); } },
                { "search_query", n => { SearchQuery = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery>(global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResultConnector>("connector", Connector);
            writer.WriteBoolValue("continue_on_failure", ContinueOnFailure);
            writer.WriteCollectionOfPrimitiveValues<string>("document_ids", DocumentIds);
            writer.WriteStringValue("error_message", ErrorMessage);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery>("search_query", SearchQuery);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
