// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>&quot;The reason a chat request has finished.- **complete**: The model finished sending a complete message.- **max_tokens**: The number of generated tokens exceeded the model&apos;s context length or the value specified via the `max_tokens` parameter.- **stop_sequence**: One of the provided `stop_sequence` entries was reached in the model&apos;s generation.- **tool_call**: The model generated a Tool Call and is expecting a Tool Message in return- **error**: The generation failed due to an internal error- **timeout**: The generation was stopped because it exceeded the allowed time limit.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatFinishReason
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "STOP_SEQUENCE")]
        #pragma warning disable CS1591
        StopSequence,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_TOKENS")]
        #pragma warning disable CS1591
        MaxTokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOOL_CALL")]
        #pragma warning disable CS1591
        ToolCall,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIMEOUT")]
        #pragma warning disable CS1591
        Timeout,
        #pragma warning restore CS1591
    }
}
