// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>- `COMPLETE` - the model sent back a finished reply- `ERROR_LIMIT` - the reply was cut off because the model reached the maximum number of tokens for its context length- `MAX_TOKENS` - the reply was cut off because the model reached the maximum number of tokens specified by the max_tokens parameter- `ERROR` - something went wrong when generating the reply- `ERROR_TOXIC` - the model generated a reply that was deemed toxic</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatStreamEndEventFinishReason
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_LIMIT")]
        #pragma warning disable CS1591
        ErrorLimit,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_TOKENS")]
        #pragma warning disable CS1591
        MaxTokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_TOXIC")]
        #pragma warning disable CS1591
        ErrorToxic,
        #pragma warning restore CS1591
    }
}
