// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>The type of citation which indicates what part of the response the citation is for.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CitationType
    {
        [EnumMember(Value = "TEXT_CONTENT")]
        #pragma warning disable CS1591
        TEXT_CONTENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "THINKING_CONTENT")]
        #pragma warning disable CS1591
        THINKING_CONTENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLAN")]
        #pragma warning disable CS1591
        PLAN,
        #pragma warning restore CS1591
    }
}
