// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>One of the Cohere API endpoints that the model can be used with.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CompatibleEndpoint
    {
        [EnumMember(Value = "chat")]
        #pragma warning disable CS1591
        Chat,
        #pragma warning restore CS1591
        [EnumMember(Value = "embed")]
        #pragma warning disable CS1591
        Embed,
        #pragma warning restore CS1591
        [EnumMember(Value = "classify")]
        #pragma warning disable CS1591
        Classify,
        #pragma warning restore CS1591
        [EnumMember(Value = "summarize")]
        #pragma warning disable CS1591
        Summarize,
        #pragma warning restore CS1591
        [EnumMember(Value = "rerank")]
        #pragma warning disable CS1591
        Rerank,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate")]
        #pragma warning disable CS1591
        Rate,
        #pragma warning restore CS1591
        [EnumMember(Value = "generate")]
        #pragma warning disable CS1591
        Generate,
        #pragma warning restore CS1591
    }
}
