// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// A connector allows you to integrate data sources with the &apos;/chat&apos; endpoint to create grounded generations with citations to the data source.documents to help answer users.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Connector : IAdditionalDataHolder, IParsable
    {
        /// <summary>Whether the connector is active or not.</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The OAuth status for the user making the request. One of [&quot;valid&quot;, &quot;expired&quot;, &quot;&quot;]. Empty string (field is omitted) means the user has not authorized the connector yet.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.Connector_auth_status? AuthStatus { get; set; }
        /// <summary>The type of authentication/authorization used by the connector. Possible values: [oauth, service_auth]</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthType { get; set; }
#nullable restore
#else
        public string AuthType { get; set; }
#endif
        /// <summary>Whether a chat request should continue or not if the request to this connector fails.</summary>
        public bool? ContinueOnFailure { get; set; }
        /// <summary>The UTC time at which the connector was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A description of the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A list of fields to exclude from the prompt (fields remain in the document).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Excludes { get; set; }
#nullable restore
#else
        public List<string> Excludes { get; set; }
#endif
        /// <summary>The unique identifier of the connector (used in both `/connectors` &amp; `/chat` endpoints).This is automatically created from the name of the connector upon registration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>A human-readable name for the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The OAuth 2.0 configuration for the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ConnectorOAuth? Oauth { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ConnectorOAuth Oauth { get; set; }
#endif
        /// <summary>The organization to which this connector belongs. This is automatically set tothe organization of the user who created the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>The UTC time at which the connector was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The URL of the connector that will be used to search for documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Connector"/> and sets the default values.
        /// </summary>
        public Connector()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Connector"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.Connector CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.Connector();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "auth_status", n => { AuthStatus = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.Connector_auth_status>(); } },
                { "auth_type", n => { AuthType = n.GetStringValue(); } },
                { "continue_on_failure", n => { ContinueOnFailure = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "excludes", n => { Excludes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "oauth", n => { Oauth = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ConnectorOAuth>(global::Soenneker.Cohere.OpenApiClient.Models.ConnectorOAuth.CreateFromDiscriminatorValue); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.Connector_auth_status>("auth_status", AuthStatus);
            writer.WriteStringValue("auth_type", AuthType);
            writer.WriteBoolValue("continue_on_failure", ContinueOnFailure);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("excludes", Excludes);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ConnectorOAuth>("oauth", Oauth);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
