// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>One of `START|END` to specify how the API will handle inputs longer than the maximum token length.Passing `START` will discard the start of the input. `END` will discard the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateEmbedJobRequest_truncate
    {
        [EnumMember(Value = "START")]
        #pragma warning disable CS1591
        START,
        #pragma warning restore CS1591
        [EnumMember(Value = "END")]
        #pragma warning disable CS1591
        END,
        #pragma warning restore CS1591
    }
}
