// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateEmbedJobRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of a [Dataset](https://docs.cohere.com/docs/datasets). The Dataset must be of type `embed-input` and must have a validation status `Validated`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatasetId { get; set; }
#nullable restore
#else
        public string DatasetId { get; set; }
#endif
        /// <summary>Specifies the types of embeddings you want to get back. Not required and default is None, which returns the Embed Floats response type. Can be one or more of the following types.* `&quot;float&quot;`: Use this when you want to get back the default float embeddings. Valid for all models.* `&quot;int8&quot;`: Use this when you want to get back signed int8 embeddings. Valid for v3 and newer model versions.* `&quot;uint8&quot;`: Use this when you want to get back unsigned int8 embeddings. Valid for v3 and newer model versions.* `&quot;binary&quot;`: Use this when you want to get back signed binary embeddings. Valid for v3 and newer model versions.* `&quot;ubinary&quot;`: Use this when you want to get back unsigned binary embeddings. Valid for v3 and newer model versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.EmbeddingType?>? EmbeddingTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.EmbeddingType?> EmbeddingTypes { get; set; }
#endif
        /// <summary>Specifies the type of input passed to the model. Required for embedding models v3 and higher.- `&quot;search_document&quot;`: Used for embeddings stored in a vector database for search use-cases.- `&quot;search_query&quot;`: Used for embeddings of search queries run against a vector DB to find relevant documents.- `&quot;classification&quot;`: Used for embeddings passed through a text classifier.- `&quot;clustering&quot;`: Used for the embeddings run through a clustering algorithm.- `&quot;image&quot;`: Used for embeddings with image input.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.EmbedInputType? InputType { get; set; }
        /// <summary>ID of the embedding model.Available models and corresponding embedding dimensions:- `embed-english-v3.0` : 1024- `embed-multilingual-v3.0` : 1024- `embed-english-light-v3.0` : 384- `embed-multilingual-light-v3.0` : 384</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The name of the embed job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>One of `START|END` to specify how the API will handle inputs longer than the maximum token length.Passing `START` will discard the start of the input. `END` will discard the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest_truncate? Truncate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest"/> and sets the default values.
        /// </summary>
        public CreateEmbedJobRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Truncate = global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest_truncate.END;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dataset_id", n => { DatasetId = n.GetStringValue(); } },
                { "embedding_types", n => { EmbeddingTypes = n.GetCollectionOfEnumValues<global::Soenneker.Cohere.OpenApiClient.Models.EmbeddingType>()?.AsList(); } },
                { "input_type", n => { InputType = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.EmbedInputType>(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "truncate", n => { Truncate = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest_truncate>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dataset_id", DatasetId);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Cohere.OpenApiClient.Models.EmbeddingType>("embedding_types", EmbeddingTypes);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.EmbedInputType>("input_type", InputType);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest_truncate>("truncate", Truncate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
