// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>The type of the dataset</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatasetType
    {
        [EnumMember(Value = "embed-input")]
        #pragma warning disable CS1591
        EmbedInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "embed-result")]
        #pragma warning disable CS1591
        EmbedResult,
        #pragma warning restore CS1591
        [EnumMember(Value = "cluster-result")]
        #pragma warning disable CS1591
        ClusterResult,
        #pragma warning restore CS1591
        [EnumMember(Value = "cluster-outliers")]
        #pragma warning disable CS1591
        ClusterOutliers,
        #pragma warning restore CS1591
        [EnumMember(Value = "reranker-finetune-input")]
        #pragma warning disable CS1591
        RerankerFinetuneInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "single-label-classification-finetune-input")]
        #pragma warning disable CS1591
        SingleLabelClassificationFinetuneInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat-finetune-input")]
        #pragma warning disable CS1591
        ChatFinetuneInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi-label-classification-finetune-input")]
        #pragma warning disable CS1591
        MultiLabelClassificationFinetuneInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-chat-input")]
        #pragma warning disable CS1591
        BatchChatInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-openai-chat-input")]
        #pragma warning disable CS1591
        BatchOpenaiChatInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-embed-v2-input")]
        #pragma warning disable CS1591
        BatchEmbedV2Input,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch-chat-v2-input")]
        #pragma warning disable CS1591
        BatchChatV2Input,
        #pragma warning restore CS1591
    }
}
