// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>The truncation option used</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmbedJobTruncate
    {
        [EnumMember(Value = "START")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "END")]
        #pragma warning disable CS1591
        End,
        #pragma warning restore CS1591
    }
}
