// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbeddingType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        Float,
        #pragma warning restore CS1591
        [EnumMember(Value = "int8")]
        #pragma warning disable CS1591
        Int8,
        #pragma warning restore CS1591
        [EnumMember(Value = "uint8")]
        #pragma warning disable CS1591
        Uint8,
        #pragma warning restore CS1591
        [EnumMember(Value = "binary")]
        #pragma warning disable CS1591
        Binary,
        #pragma warning restore CS1591
        [EnumMember(Value = "ubinary")]
        #pragma warning disable CS1591
        Ubinary,
        #pragma warning restore CS1591
        [EnumMember(Value = "base64")]
        #pragma warning disable CS1591
        Base64,
        #pragma warning restore CS1591
    }
}
