// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbedContentType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_url")]
        #pragma warning disable CS1591
        Image_url,
        #pragma warning restore CS1591
    }
}
