// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbedByTypeResponseResponseType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "embeddings_floats")]
        #pragma warning disable CS1591
        EmbeddingsFloats,
        #pragma warning restore CS1591
        [EnumMember(Value = "embeddings_by_type")]
        #pragma warning disable CS1591
        EmbeddingsByType,
        #pragma warning restore CS1591
    }
}
