// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FinishReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "STOP_SEQUENCE")]
        #pragma warning disable CS1591
        StopSequence,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_TOXIC")]
        #pragma warning disable CS1591
        ErrorToxic,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_LIMIT")]
        #pragma warning disable CS1591
        ErrorLimit,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_CANCEL")]
        #pragma warning disable CS1591
        UserCancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_TOKENS")]
        #pragma warning disable CS1591
        MaxTokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIMEOUT")]
        #pragma warning disable CS1591
        Timeout,
        #pragma warning restore CS1591
    }
}
