// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FinishReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        COMPLETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "STOP_SEQUENCE")]
        #pragma warning disable CS1591
        STOP_SEQUENCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_TOXIC")]
        #pragma warning disable CS1591
        ERROR_TOXIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_LIMIT")]
        #pragma warning disable CS1591
        ERROR_LIMIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_CANCEL")]
        #pragma warning disable CS1591
        USER_CANCEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_TOKENS")]
        #pragma warning disable CS1591
        MAX_TOKENS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIMEOUT")]
        #pragma warning disable CS1591
        TIMEOUT,
        #pragma warning restore CS1591
    }
}
