// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// Default sampling parameters for this model when omitted from API requests.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetModelResponse_sampling_defaults : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The frequency_penalty property</summary>
        public float? FrequencyPenalty { get; set; }
        /// <summary>The k property</summary>
        public int? K { get; set; }
        /// <summary>The max_tokens_per_doc property</summary>
        public int? MaxTokensPerDoc { get; set; }
        /// <summary>The p property</summary>
        public float? P { get; set; }
        /// <summary>The presence_penalty property</summary>
        public float? PresencePenalty { get; set; }
        /// <summary>The temperature property</summary>
        public float? Temperature { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.GetModelResponse_sampling_defaults"/> and sets the default values.
        /// </summary>
        public GetModelResponse_sampling_defaults()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.GetModelResponse_sampling_defaults"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.GetModelResponse_sampling_defaults CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.GetModelResponse_sampling_defaults();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "frequency_penalty", n => { FrequencyPenalty = n.GetFloatValue(); } },
                { "k", n => { K = n.GetIntValue(); } },
                { "max_tokens_per_doc", n => { MaxTokensPerDoc = n.GetIntValue(); } },
                { "p", n => { P = n.GetFloatValue(); } },
                { "presence_penalty", n => { PresencePenalty = n.GetFloatValue(); } },
                { "temperature", n => { Temperature = n.GetFloatValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("frequency_penalty", FrequencyPenalty);
            writer.WriteIntValue("k", K);
            writer.WriteIntValue("max_tokens_per_doc", MaxTokensPerDoc);
            writer.WriteFloatValue("p", P);
            writer.WriteFloatValue("presence_penalty", PresencePenalty);
            writer.WriteFloatValue("temperature", Temperature);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
