// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>The combination of LoRA modules to target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum LoraTargetModules
    {
        [EnumMember(Value = "LORA_TARGET_MODULES_UNSPECIFIED")]
        #pragma warning disable CS1591
        LORA_TARGET_MODULES_UNSPECIFIED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LORA_TARGET_MODULES_QV")]
        #pragma warning disable CS1591
        LORA_TARGET_MODULES_QV,
        #pragma warning restore CS1591
        [EnumMember(Value = "LORA_TARGET_MODULES_QKVO")]
        #pragma warning disable CS1591
        LORA_TARGET_MODULES_QKVO,
        #pragma warning restore CS1591
        [EnumMember(Value = "LORA_TARGET_MODULES_QKVO_FFN")]
        #pragma warning disable CS1591
        LORA_TARGET_MODULES_QKVO_FFN,
        #pragma warning restore CS1591
    }
}
