// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NonStreamedChatResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of previous messages between the user and the model, meant to give the model conversational context for responding to the user&apos;s `message`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Message>? ChatHistory { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Message> ChatHistory { get; set; }
#endif
        /// <summary>Inline citations for the generated reply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatCitation>? Citations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatCitation> Citations { get; set; }
#endif
        /// <summary>Documents seen by the model when generating the reply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>? Documents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument> Documents { get; set; }
#endif
        /// <summary>The finish_reason property</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.FinishReason? FinishReason { get; set; }
        /// <summary>Unique identifier for the generated reply. Useful for submitting feedback.</summary>
        public Guid? GenerationId { get; set; }
        /// <summary>Denotes that a search for documents is required during the RAG flow.</summary>
        public bool? IsSearchRequired { get; set; }
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta Meta { get; set; }
#endif
        /// <summary>Unique identifier for the response.</summary>
        public Guid? ResponseId { get; set; }
        /// <summary>Generated search queries, meant to be used as part of the RAG flow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery>? SearchQueries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery> SearchQueries { get; set; }
#endif
        /// <summary>Documents retrieved from each of the conducted searches.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult>? SearchResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult> SearchResults { get; set; }
#endif
        /// <summary>Contents of the reply generated by the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The tool_calls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolCall>? ToolCalls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolCall> ToolCalls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.NonStreamedChatResponse"/> and sets the default values.
        /// </summary>
        public NonStreamedChatResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.NonStreamedChatResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.NonStreamedChatResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.NonStreamedChatResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chat_history", n => { ChatHistory = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Message>(global::Soenneker.Cohere.OpenApiClient.Models.Message.CreateFromDiscriminatorValue)?.AsList(); } },
                { "citations", n => { Citations = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatCitation>(global::Soenneker.Cohere.OpenApiClient.Models.ChatCitation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>(global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument.CreateFromDiscriminatorValue)?.AsList(); } },
                { "finish_reason", n => { FinishReason = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.FinishReason>(); } },
                { "generation_id", n => { GenerationId = n.GetGuidValue(); } },
                { "is_search_required", n => { IsSearchRequired = n.GetBoolValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta>(global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta.CreateFromDiscriminatorValue); } },
                { "response_id", n => { ResponseId = n.GetGuidValue(); } },
                { "search_queries", n => { SearchQueries = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery>(global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery.CreateFromDiscriminatorValue)?.AsList(); } },
                { "search_results", n => { SearchResults = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult>(global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "tool_calls", n => { ToolCalls = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolCall>(global::Soenneker.Cohere.OpenApiClient.Models.ToolCall.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Message>("chat_history", ChatHistory);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatCitation>("citations", Citations);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>("documents", Documents);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.FinishReason>("finish_reason", FinishReason);
            writer.WriteGuidValue("generation_id", GenerationId);
            writer.WriteBoolValue("is_search_required", IsSearchRequired);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ApiMeta>("meta", Meta);
            writer.WriteGuidValue("response_id", ResponseId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchQuery>("search_queries", SearchQueries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatSearchResult>("search_results", SearchResults);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolCall>("tool_calls", ToolCalls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
