// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// A bounding box with pixel coordinates on the source document image.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseBoundingBox : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>X coordinate of the bottom-right corner.</summary>
        public int? BottomRightX { get; set; }
        /// <summary>Y coordinate of the bottom-right corner.</summary>
        public int? BottomRightY { get; set; }
        /// <summary>X coordinate of the top-left corner.</summary>
        public int? TopLeftX { get; set; }
        /// <summary>Y coordinate of the top-left corner.</summary>
        public int? TopLeftY { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox"/> and sets the default values.
        /// </summary>
        public ParseBoundingBox()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bottom_right_x", n => { BottomRightX = n.GetIntValue(); } },
                { "bottom_right_y", n => { BottomRightY = n.GetIntValue(); } },
                { "top_left_x", n => { TopLeftX = n.GetIntValue(); } },
                { "top_left_y", n => { TopLeftY = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bottom_right_x", BottomRightX);
            writer.WriteIntValue("bottom_right_y", BottomRightY);
            writer.WriteIntValue("top_left_x", TopLeftX);
            writer.WriteIntValue("top_left_y", TopLeftY);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
