// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>Table serialization format.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParseTableContentType
    {
        [EnumMember(Value = "html")]
        #pragma warning disable CS1591
        Html,
        #pragma warning restore CS1591
    }
}
