// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Parsev2Request : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Document to parse. Currently only `image_url` documents are supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseDocument? Document { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseDocument Document { get; set; }
#endif
        /// <summary>The name of a compatible Cohere parse model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Selects the page payload shape in the response. Defaults to `&quot;markdown&quot;`.- `&quot;markdown&quot;`: each page includes markdown content. Tables are inlined as  HTML, and images are referenced as `![&lt;description&gt;](&lt;image_id&gt;)` with  matching entries in `page.markdown.images`.- `&quot;blocks&quot;`: each page includes an ordered `blocks` array of text, image,  and table content regions, including bounding boxes where available.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseOutputFormat? OutputFormat { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Parsev2Request"/> and sets the default values.
        /// </summary>
        public Parsev2Request()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Parsev2Request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.Parsev2Request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.Parsev2Request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "document", n => { Document = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseDocument>(global::Soenneker.Cohere.OpenApiClient.Models.ParseDocument.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "output_format", n => { OutputFormat = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseOutputFormat>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseDocument>("document", Document);
            writer.WriteStringValue("model", Model);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseOutputFormat>("output_format", OutputFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
