// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// Payload for an image block.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseImageBlock : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A bounding box with pixel coordinates on the source document image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox? BoundingBox { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox BoundingBox { get; set; }
#endif
        /// <summary>A bounding box with coordinates in [0, 1] relative to the source page (modelcoordinates are thousandths of page width/height).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBoxNormalized? BoundingBoxNormalized { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBoxNormalized BoundingBoxNormalized { get; set; }
#endif
        /// <summary>Image element category.</summary>
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseImageCategory? Category { get; set; }
        /// <summary>Model-generated description of the image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Unique identifier for the image within the page (for example `img-0`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseImageBlock"/> and sets the default values.
        /// </summary>
        public ParseImageBlock()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseImageBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ParseImageBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.ParseImageBlock();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounding_box", n => { BoundingBox = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox>(global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox.CreateFromDiscriminatorValue); } },
                { "bounding_box_normalized", n => { BoundingBoxNormalized = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBoxNormalized>(global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBoxNormalized.CreateFromDiscriminatorValue); } },
                { "category", n => { Category = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseImageCategory>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBox>("bounding_box", BoundingBox);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseBoundingBoxNormalized>("bounding_box_normalized", BoundingBoxNormalized);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseImageCategory>("category", Category);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
