// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock"/>, <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock"/>, <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseBlock : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock? ParseImageContentBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock ParseImageContentBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock? ParseTableContentBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock ParseTableContentBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock? ParseTextContentBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock ParseTextContentBlock { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ParseBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ParseBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cohere.OpenApiClient.Models.ParseBlock();
            if("image".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ParseImageContentBlock = new global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock();
            }
            else if("ParseTableContentBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ParseTableContentBlock = new global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock();
            }
            else if("ParseTextContentBlock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ParseTextContentBlock = new global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ParseImageContentBlock != null)
            {
                return ParseImageContentBlock.GetFieldDeserializers();
            }
            else if(ParseTableContentBlock != null)
            {
                return ParseTableContentBlock.GetFieldDeserializers();
            }
            else if(ParseTextContentBlock != null)
            {
                return ParseTextContentBlock.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ParseImageContentBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseImageContentBlock>(null, ParseImageContentBlock);
            }
            else if(ParseTableContentBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseTableContentBlock>(null, ParseTableContentBlock);
            }
            else if(ParseTextContentBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ParseTextContentBlock>(null, ParseTextContentBlock);
            }
        }
    }
}
#pragma warning restore CS0618
