// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat"/>, <see cref="global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseFormat : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat? ChatTextResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat ChatTextResponseFormat { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat? JSONResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat JSONResponseFormat { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat();
            if("text".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ChatTextResponseFormat = new global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat();
            }
            else if("json_object".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.JSONResponseFormat = new global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ChatTextResponseFormat != null)
            {
                return ChatTextResponseFormat.GetFieldDeserializers();
            }
            else if(JSONResponseFormat != null)
            {
                return JSONResponseFormat.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ChatTextResponseFormat != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatTextResponseFormat>(null, ChatTextResponseFormat);
            }
            else if(JSONResponseFormat != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.JSONResponseFormat>(null, JSONResponseFormat);
            }
        }
    }
}
#pragma warning restore CS0618
