// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>
    /// FinetunedModel settings such as dataset, hyperparameters...
    /// </summary>
    [Obsolete("")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Settings : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The base model to fine-tune.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.BaseModel? BaseModel { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.BaseModel BaseModel { get; set; }
#endif
        /// <summary>The data used for training and evaluating the fine-tuned model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DatasetId { get; set; }
#nullable restore
#else
        public string DatasetId { get; set; }
#endif
        /// <summary>Fine-tuning hyper-parameters.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Hyperparameters? Hyperparameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Hyperparameters Hyperparameters { get; set; }
#endif
        /// <summary>read-only. Whether the model is single-label or multi-label (only for classification).</summary>
        public bool? MultiLabel { get; private set; }
        /// <summary>The Weights &amp; Biases configuration (Chat fine-tuning only).</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.WandbConfig? Wandb { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.WandbConfig Wandb { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Settings"/> and sets the default values.
        /// </summary>
        public Settings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.Settings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.Settings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.Settings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base_model", n => { BaseModel = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.BaseModel>(global::Soenneker.Cohere.OpenApiClient.Models.BaseModel.CreateFromDiscriminatorValue); } },
                { "dataset_id", n => { DatasetId = n.GetStringValue(); } },
                { "hyperparameters", n => { Hyperparameters = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Hyperparameters>(global::Soenneker.Cohere.OpenApiClient.Models.Hyperparameters.CreateFromDiscriminatorValue); } },
                { "multi_label", n => { MultiLabel = n.GetBoolValue(); } },
                { "wandb", n => { Wandb = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.WandbConfig>(global::Soenneker.Cohere.OpenApiClient.Models.WandbConfig.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.BaseModel>("base_model", BaseModel);
            writer.WriteStringValue("dataset_id", DatasetId);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Hyperparameters>("hyperparameters", Hyperparameters);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.WandbConfig>("wandb", Wandb);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
