// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>read-only. Current stage in the life-cycle of the fine-tuned model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum Status
    {
        [EnumMember(Value = "STATUS_UNSPECIFIED")]
        #pragma warning disable CS1591
        StatusUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_FINETUNING")]
        #pragma warning disable CS1591
        StatusFinetuning,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_DEPLOYING_API")]
        #pragma warning disable CS1591
        StatusDeployingApi,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_READY")]
        #pragma warning disable CS1591
        StatusReady,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_FAILED")]
        #pragma warning disable CS1591
        StatusFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_DELETED")]
        #pragma warning disable CS1591
        StatusDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_TEMPORARILY_OFFLINE")]
        #pragma warning disable CS1591
        StatusTemporarilyOffline,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_PAUSED")]
        #pragma warning disable CS1591
        StatusPaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATUS_QUEUED")]
        #pragma warning disable CS1591
        StatusQueued,
        #pragma warning restore CS1591
    }
}
