// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>Deprecated: The fine-tuning strategy.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum Strategy
    {
        [EnumMember(Value = "STRATEGY_UNSPECIFIED")]
        #pragma warning disable CS1591
        StrategyUnspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRATEGY_VANILLA")]
        #pragma warning disable CS1591
        StrategyVanilla,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRATEGY_TFEW")]
        #pragma warning disable CS1591
        StrategyTfew,
        #pragma warning restore CS1591
    }
}
