// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>- `COMPLETE` - the model sent back a finished reply- `ERROR_LIMIT` - the reply was cut off because the model reached the maximum number of tokens for its context length- `MAX_TOKENS` - the reply was cut off because the model reached the maximum number of tokens specified by the max_tokens parameter- `ERROR` - something went wrong when generating the reply- `ERROR_TOXIC` - the model generated a reply that was deemed toxic</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StreamedChatResponse_finish_reason
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        COMPLETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_LIMIT")]
        #pragma warning disable CS1591
        ERROR_LIMIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_TOKENS")]
        #pragma warning disable CS1591
        MAX_TOKENS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_TOXIC")]
        #pragma warning disable CS1591
        ERROR_TOXIC,
        #pragma warning restore CS1591
    }
}
