// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StreamedChatResponseV2_event_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "stream-start")]
        #pragma warning disable CS1591
        StreamStart,
        #pragma warning restore CS1591
        [EnumMember(Value = "search-queries-generation")]
        #pragma warning disable CS1591
        SearchQueriesGeneration,
        #pragma warning restore CS1591
        [EnumMember(Value = "search-results")]
        #pragma warning disable CS1591
        SearchResults,
        #pragma warning restore CS1591
        [EnumMember(Value = "text-generation")]
        #pragma warning disable CS1591
        TextGeneration,
        #pragma warning restore CS1591
        [EnumMember(Value = "citation-generation")]
        #pragma warning disable CS1591
        CitationGeneration,
        #pragma warning restore CS1591
        [EnumMember(Value = "stream-end")]
        #pragma warning disable CS1591
        StreamEnd,
        #pragma warning restore CS1591
        [EnumMember(Value = "debug")]
        #pragma warning disable CS1591
        Debug,
        #pragma warning restore CS1591
    }
}
