// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    /// <summary>One of `paragraph`, `bullets`, or `auto`, defaults to `auto`. Indicates the style in which the summary will be delivered - in a free form paragraph or in bullet points. If `auto` is selected, the best option will be picked based on the input text.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SummarizeRequestFormat
    {
        [EnumMember(Value = "paragraph")]
        #pragma warning disable CS1591
        Paragraph,
        #pragma warning restore CS1591
        [EnumMember(Value = "bullets")]
        #pragma warning disable CS1591
        Bullets,
        #pragma warning restore CS1591
    }
}
