// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateConnectorRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The continue_on_failure property</summary>
        public bool? ContinueOnFailure { get; set; }
        /// <summary>A list of fields to exclude from the prompt (fields remain in the document).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Excludes { get; set; }
#nullable restore
#else
        public List<string> Excludes { get; set; }
#endif
        /// <summary>A human-readable name for the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The OAuth 2.0 configuration for the connector. Cannot be specified if service_auth is specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorOAuth? Oauth { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorOAuth Oauth { get; set; }
#endif
        /// <summary>The service to service authentication configuration for the connector. Cannot be specified if oauth is specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorServiceAuth? ServiceAuth { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorServiceAuth ServiceAuth { get; set; }
#endif
        /// <summary>The URL of the connector that will be used to search for documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.Models.UpdateConnectorRequest"/> and sets the default values.
        /// </summary>
        public UpdateConnectorRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.UpdateConnectorRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.Models.UpdateConnectorRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.Models.UpdateConnectorRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "continue_on_failure", n => { ContinueOnFailure = n.GetBoolValue(); } },
                { "excludes", n => { Excludes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "oauth", n => { Oauth = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorOAuth>(global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorOAuth.CreateFromDiscriminatorValue); } },
                { "service_auth", n => { ServiceAuth = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorServiceAuth>(global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorServiceAuth.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("continue_on_failure", ContinueOnFailure);
            writer.WriteCollectionOfPrimitiveValues<string>("excludes", Excludes);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorOAuth>("oauth", Oauth);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CreateConnectorServiceAuth>("service_auth", ServiceAuth);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
