// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Embed
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\embed
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmbedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embed", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/embed", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint returns text embeddings. An embedding is a list of floating point numbers that captures semantic information about the text that it represents.Embeddings can be used to create text classifiers as well as empower semantic search. To learn more about embeddings, see the embedding page.If you want to learn more how to use the embedding model, have a look at the [Semantic Search Guide](https://docs.cohere.com/docs/semantic-search).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse498Error">When receiving a 498 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse499Error">When receiving a 499 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse501Error">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse?> PostAsync(global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse> PostAsync(global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse429Error.CreateFromDiscriminatorValue },
                { "498", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse498Error.CreateFromDiscriminatorValue },
                { "499", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse499Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse500Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse501Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse>(requestInfo, global::Soenneker.Cohere.OpenApiClient.Models.EmbedByTypeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint returns text embeddings. An embedding is a list of floating point numbers that captures semantic information about the text that it represents.Embeddings can be used to create text classifiers as well as empower semantic search. To learn more about embeddings, see the embedding page.If you want to learn more how to use the embedding model, have a look at the [Semantic Search Guide](https://docs.cohere.com/docs/semantic-search).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cohere.OpenApiClient.V2.Embed.EmbedRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
