// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Finetuned_model_PatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp for the completed fine-tuning.</summary>
        public DateTimeOffset? CompletedAt { get; private set; }
        /// <summary>Creation timestamp.</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>User ID of the creator.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; private set; }
#nullable restore
#else
        public string CreatorId { get; private set; }
#endif
        /// <summary>Deprecated: Timestamp for the latest request to this fine-tuned model.</summary>
        public DateTimeOffset? LastUsed { get; private set; }
        /// <summary>FinetunedModel name (e.g. `foobar`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Organization ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; private set; }
#nullable restore
#else
        public string OrganizationId { get; private set; }
#endif
        /// <summary>FinetunedModel settings such as dataset, hyperparameters...</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Settings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Settings Settings { get; set; }
#endif
        /// <summary>Current stage in the life-cycle of the fine-tuned model.</summary>
        [Obsolete("")]
        public global::Soenneker.Cohere.OpenApiClient.Models.Status? Status { get; private set; }
        /// <summary>Latest update timestamp.</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.Item.Finetuned_model_PatchRequestBody"/> and sets the default values.
        /// </summary>
        public Finetuned_model_PatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::Soenneker.Cohere.OpenApiClient.Models.Status.STATUS_UNSPECIFIED;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.Item.Finetuned_model_PatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.Item.Finetuned_model_PatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.Item.Finetuned_model_PatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "last_used", n => { LastUsed = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Settings>(global::Soenneker.Cohere.OpenApiClient.Models.Settings.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.Models.Status>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Settings>("settings", Settings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
