// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Finetuning
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\finetuning
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FinetuningRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The finetunedModels property</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.FinetunedModelsRequestBuilder FinetunedModels
        {
            get => new global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetunedModels.FinetunedModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetuningRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinetuningRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/finetuning", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Finetuning.FinetuningRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinetuningRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/finetuning", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
