// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Rerank
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RerankPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of document objects or strings to rerank.If a document is provided the text fields is required and all other fields will be preserved in the response.The total max chunks (length of documents * max_chunks_per_doc) must be less than 10000.We recommend a maximum of 1,000 documents for optimal endpoint performance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Documents { get; set; }
#nullable restore
#else
        public List<string> Documents { get; set; }
#endif
        /// <summary>The maximum number of chunks to produce internally from a document</summary>
        public int? MaxChunksPerDoc { get; set; }
        /// <summary>The identifier of the model to use, eg `rerank-v3.5`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The search query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>If a JSON object is provided, you can specify which keys you would like to have considered for reranking. The model will rerank based on order of the fields passed in (i.e. rank_fields=[&apos;title&apos;,&apos;author&apos;,&apos;text&apos;] will rerank using the values in title, author, text  sequentially. If the length of title, author, and text exceeds the context length of the model, the chunking will not re-consider earlier fields). If not provided, the model will use the default text field for ranking.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RankFields { get; set; }
#nullable restore
#else
        public List<string> RankFields { get; set; }
#endif
        /// <summary>- If false, returns results without the doc text - the api will return a list of {index, relevance score} where index is inferred from the list passed into the request.- If true, returns results with the doc text passed in - the api will return an ordered list of {index, text, relevance score} where index + text refers to the list passed into the request.</summary>
        public bool? ReturnDocuments { get; set; }
        /// <summary>The number of most relevant documents or indices to return, defaults to the length of the documents</summary>
        public int? TopN { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Rerank.RerankPostRequestBody"/> and sets the default values.
        /// </summary>
        public RerankPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Rerank.RerankPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Rerank.RerankPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Rerank.RerankPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "documents", n => { Documents = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "max_chunks_per_doc", n => { MaxChunksPerDoc = n.GetIntValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "rank_fields", n => { RankFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "return_documents", n => { ReturnDocuments = n.GetBoolValue(); } },
                { "top_n", n => { TopN = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("documents", Documents);
            writer.WriteIntValue("max_chunks_per_doc", MaxChunksPerDoc);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("query", Query);
            writer.WriteCollectionOfPrimitiveValues<string>("rank_fields", RankFields);
            writer.WriteBoolValue("return_documents", ReturnDocuments);
            writer.WriteIntValue("top_n", TopN);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
