// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Summarize
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SummarizePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A free-form instruction for modifying how the summaries get generated. Should complete the sentence &quot;Generate a summary _&quot;. Eg. &quot;focusing on the next steps&quot; or &quot;written by Yoda&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalCommand { get; set; }
#nullable restore
#else
        public string AdditionalCommand { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>One of `low`, `medium`, `high`, or `auto`, defaults to `auto`. Controls how close to the original text the summary is. `high` extractiveness summaries will lean towards reusing sentences verbatim, while `low` extractiveness summaries will tend to paraphrase more. If `auto` is selected, the best option will be picked based on the input text.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_extractiveness? Extractiveness { get; set; }
        /// <summary>One of `paragraph`, `bullets`, or `auto`, defaults to `auto`. Indicates the style in which the summary will be delivered - in a free form paragraph or in bullet points. If `auto` is selected, the best option will be picked based on the input text.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_format? Format { get; set; }
        /// <summary>One of `short`, `medium`, `long`, or `auto` defaults to `auto`. Indicates the approximate length of the summary. If `auto` is selected, the best option will be picked based on the input text.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_length? Length { get; set; }
        /// <summary>The identifier of the model to generate the summary with. Currently available models are `command` (default), `command-nightly` (experimental), `command-light`, and `command-light-nightly` (experimental). Smaller, &quot;light&quot; models are faster, while larger models will perform better.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Ranges from 0 to 5. Controls the randomness of the output. Lower values tend to generate more “predictable” output, while higher values tend to generate more “creative” output. The sweet spot is typically between 0 and 1.</summary>
        public double? Temperature { get; set; }
        /// <summary>The text to generate a summary for. Can be up to 100,000 characters long. Currently the only supported language is English.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody"/> and sets the default values.
        /// </summary>
        public SummarizePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Extractiveness = global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_extractiveness.Low;
            Format = global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_format.Paragraph;
            Length = global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_length.Medium;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_command", n => { AdditionalCommand = n.GetStringValue(); } },
                { "extractiveness", n => { Extractiveness = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_extractiveness>(); } },
                { "format", n => { Format = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_format>(); } },
                { "length", n => { Length = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_length>(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("additional_command", AdditionalCommand);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_extractiveness>("extractiveness", Extractiveness);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_format>("format", Format);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Summarize.SummarizePostRequestBody_length>("length", Length);
            writer.WriteStringValue("model", Model);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteStringValue("text", Text);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
