// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Chat
{
    /// <summary>Used to control whether or not the model will be forced to use a tool when answering. When `REQUIRED` is specified, the model will be forced to use at least one of the user-defined tools, and the `tools` parameter must be passed in the request.When `NONE` is specified, the model will be forced **not** to use one of the specified tools, and give a direct response.If tool_choice isn&apos;t specified, then the model is free to choose whether to use the specified tools or not.**Note**: This parameter is only compatible with models [Command-r7b](https://docs.cohere.com/v2/docs/command-r7b) and newer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatPostRequestBody_tool_choice
    {
        [EnumMember(Value = "REQUIRED")]
        #pragma warning disable CS1591
        REQUIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
    }
}
