// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Chat
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Options for controlling citation generation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.CitationOptions? CitationOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.CitationOptions CitationOptions { get; set; }
#endif
        /// <summary>A list of relevant documents that the model can cite to generate a more accurate reply. Each document is either a string or document object with content and metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Documents { get; set; }
#nullable restore
#else
        public List<string> Documents { get; set; }
#endif
        /// <summary>Defaults to `0.0`, min value of `0.0`, max value of `1.0`.Used to reduce repetitiveness of generated tokens. The higher the value, the stronger a penalty is applied to previously present tokens, proportional to how many times they have already appeared in the prompt or prior generation.</summary>
        public float? FrequencyPenalty { get; set; }
        /// <summary>Ensures that only the top `k` most likely tokens are considered for generation at each step. When `k` is set to `0`, k-sampling is disabled.Defaults to `0`, min value of `0`, max value of `500`.</summary>
        public int? K { get; set; }
        /// <summary>Defaults to `false`. When set to `true`, the log probabilities of the generated tokens will be included in the response.</summary>
        public bool? Logprobs { get; set; }
        /// <summary>The maximum number of output tokens the model will generate in the response. If not set, `max_tokens` defaults to the model&apos;s maximum output token limit. You can find the maximum output token limits for each model in the [model documentation](https://docs.cohere.com/docs/models).**Note**: Setting a low value may result in incomplete generations. In such cases, the `finish_reason` field in the response will be set to `&quot;MAX_TOKENS&quot;`.**Note**: If `max_tokens` is set higher than the model&apos;s maximum output token limit, the generation will be capped at that model-specific maximum limit.</summary>
        public int? MaxTokens { get; set; }
        /// <summary>A list of chat messages in chronological order, representing a conversation between the user and the model.Messages can be from `User`, `Assistant`, `Tool` and `System` roles. Learn more about messages and roles in [the Chat API guide](https://docs.cohere.com/v2/docs/chat-api).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatMessageV2>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatMessageV2> Messages { get; set; }
#endif
        /// <summary>The name of a compatible [Cohere model](https://docs.cohere.com/v2/docs/models).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Ensures that only the most likely tokens, with total probability mass of `p`, are considered for generation at each step. If both `k` and `p` are enabled, `p` acts after `k`.Defaults to `0.75`. min value of `0.01`, max value of `0.99`.</summary>
        public float? P { get; set; }
        /// <summary>Defaults to `0.0`, min value of `0.0`, max value of `1.0`.Used to reduce repetitiveness of generated tokens. Similar to `frequency_penalty`, except that this penalty is applied equally to all tokens that have already appeared, regardless of their exact frequencies.</summary>
        public float? PresencePenalty { get; set; }
        /// <summary>Controls how early the request is handled. Lower numbers indicate higher priority (default: 0, the highest). When the system is under load, higher-priority requests are processed first and are the least likely to be dropped.</summary>
        public int? Priority { get; set; }
        /// <summary>Configuration for forcing the model output to adhere to the specified format. Supported on [Command R](https://docs.cohere.com/v2/docs/command-r), [Command R+](https://docs.cohere.com/v2/docs/command-r-plus) and newer models.The model can be forced into outputting JSON objects by setting `{ &quot;type&quot;: &quot;json_object&quot; }`.A [JSON Schema](https://json-schema.org/) can optionally be provided, to ensure a specific structure.**Note**: When using  `{ &quot;type&quot;: &quot;json_object&quot; }` your `message` should always explicitly instruct the model to generate a JSON (eg: _&quot;Generate a JSON ...&quot;_) . Otherwise the model may end up getting stuck generating an infinite stream of characters and eventually run out of context length.**Note**: When `json_schema` is not specified, the generated object can have up to 5 layers of nesting.**Limitation**: The parameter is not supported when used in combinations with the `documents` or `tools` parameters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormatV2? ResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormatV2 ResponseFormat { get; set; }
#endif
        /// <summary>Used to select the [safety instruction](https://docs.cohere.com/v2/docs/safety-modes) inserted into the prompt. Defaults to `CONTEXTUAL`.When `OFF` is specified, the safety instruction will be omitted.Safety modes are not yet configurable in combination with `tools` and `documents` parameters.**Note**: This parameter is only compatible newer Cohere models, starting with [Command R 08-2024](https://docs.cohere.com/docs/command-r#august-2024-release) and [Command R+ 08-2024](https://docs.cohere.com/docs/command-r-plus#august-2024-release).**Note**: `command-r7b-12-2024` and newer models only support `&quot;CONTEXTUAL&quot;` and `&quot;STRICT&quot;` modes.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_safety_mode? SafetyMode { get; set; }
        /// <summary>If specified, the backend will make a best effort to sample tokensdeterministically, such that repeated requests with the sameseed and parameters should return the same result. However,determinism cannot be totally guaranteed.</summary>
        public int? Seed { get; set; }
        /// <summary>A list of up to 5 strings that the model will use to stop generation. If the model generates a string that matches any of the strings in the list, it will stop generating tokens and return the generated text up to that point not including the stop sequence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StopSequences { get; set; }
#nullable restore
#else
        public List<string> StopSequences { get; set; }
#endif
        /// <summary>Defaults to `false`.When `true`, the response will be a SSE stream of events.Streaming is beneficial for user interfaces that render the contents of the response piece by piece, as it gets generated.</summary>
        public bool? Stream { get; set; }
        /// <summary>When set to `true`, tool calls in the Assistant message will be forced to follow the tool definition strictly. Learn more in the [Structured Outputs (Tools) guide](https://docs.cohere.com/docs/structured-outputs-json#structured-outputs-tools).**Note**: The first few requests with a new set of tools will take longer to process.</summary>
        public bool? StrictTools { get; set; }
        /// <summary>Defaults to `0.3`.A non-negative float that tunes the degree of randomness in generation. Lower temperatures mean less random generations, and higher temperatures mean more random generations.Randomness can be further maximized by increasing the  value of the `p` parameter.</summary>
        public float? Temperature { get; set; }
        /// <summary>Configuration for [reasoning features](https://docs.cohere.com/docs/reasoning).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.Thinking? Thinking { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.Thinking Thinking { get; set; }
#endif
        /// <summary>Used to control whether or not the model will be forced to use a tool when answering. When `REQUIRED` is specified, the model will be forced to use at least one of the user-defined tools, and the `tools` parameter must be passed in the request.When `NONE` is specified, the model will be forced **not** to use one of the specified tools, and give a direct response.If tool_choice isn&apos;t specified, then the model is free to choose whether to use the specified tools or not.**Note**: This parameter is only compatible with models [Command-r7b](https://docs.cohere.com/v2/docs/command-r7b) and newer.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_tool_choice? ToolChoice { get; set; }
        /// <summary>A list of tools (functions) available to the model. The model response may contain &apos;tool_calls&apos; to the specified tools.Learn more in the [Tool Use guide](https://docs.cohere.com/docs/tools).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolV2>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolV2> Tools { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody"/> and sets the default values.
        /// </summary>
        public ChatPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "citation_options", n => { CitationOptions = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CitationOptions>(global::Soenneker.Cohere.OpenApiClient.Models.CitationOptions.CreateFromDiscriminatorValue); } },
                { "documents", n => { Documents = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "frequency_penalty", n => { FrequencyPenalty = n.GetFloatValue(); } },
                { "k", n => { K = n.GetIntValue(); } },
                { "logprobs", n => { Logprobs = n.GetBoolValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatMessageV2>(global::Soenneker.Cohere.OpenApiClient.Models.ChatMessageV2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "p", n => { P = n.GetFloatValue(); } },
                { "presence_penalty", n => { PresencePenalty = n.GetFloatValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "response_format", n => { ResponseFormat = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormatV2>(global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormatV2.CreateFromDiscriminatorValue); } },
                { "safety_mode", n => { SafetyMode = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_safety_mode>(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "stop_sequences", n => { StopSequences = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "strict_tools", n => { StrictTools = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetFloatValue(); } },
                { "thinking", n => { Thinking = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Thinking>(global::Soenneker.Cohere.OpenApiClient.Models.Thinking.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_tool_choice>(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolV2>(global::Soenneker.Cohere.OpenApiClient.Models.ToolV2.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.CitationOptions>("citation_options", CitationOptions);
            writer.WriteCollectionOfPrimitiveValues<string>("documents", Documents);
            writer.WriteFloatValue("frequency_penalty", FrequencyPenalty);
            writer.WriteIntValue("k", K);
            writer.WriteBoolValue("logprobs", Logprobs);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatMessageV2>("messages", Messages);
            writer.WriteStringValue("model", Model);
            writer.WriteFloatValue("p", P);
            writer.WriteFloatValue("presence_penalty", PresencePenalty);
            writer.WriteIntValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormatV2>("response_format", ResponseFormat);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_safety_mode>("safety_mode", SafetyMode);
            writer.WriteIntValue("seed", Seed);
            writer.WriteCollectionOfPrimitiveValues<string>("stop_sequences", StopSequences);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteBoolValue("strict_tools", StrictTools);
            writer.WriteFloatValue("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.Thinking>("thinking", Thinking);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody_tool_choice>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolV2>("tools", Tools);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
