// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Chat
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\chat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/chat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/chat", rawUrl)
        {
        }
        /// <summary>
        /// Generates a text response to a user message and streams it down, token by token. To learn how to use the Chat API with streaming follow our [Text Generation guides](https://docs.cohere.com/v2/docs/chat-api).Follow the [Migration Guide](https://docs.cohere.com/v2/docs/migrating-v1-to-v2) for instructions on moving from API v1 to API v2.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat498Error">When receiving a 498 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat499Error">When receiving a 499 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat501Error">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Chat504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse?> PostAsync(global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse> PostAsync(global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.Chat400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.Chat401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.Chat403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.Chat404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Cohere.OpenApiClient.Models.Chat422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cohere.OpenApiClient.Models.Chat429Error.CreateFromDiscriminatorValue },
                { "498", global::Soenneker.Cohere.OpenApiClient.Models.Chat498Error.CreateFromDiscriminatorValue },
                { "499", global::Soenneker.Cohere.OpenApiClient.Models.Chat499Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.Chat500Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Cohere.OpenApiClient.Models.Chat501Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.Chat503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Cohere.OpenApiClient.Models.Chat504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse>(requestInfo, global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Generates a text response to a user message and streams it down, token by token. To learn how to use the Chat API with streaming follow our [Text Generation guides](https://docs.cohere.com/v2/docs/chat-api).Follow the [Migration Guide](https://docs.cohere.com/v2/docs/migrating-v1-to-v2) for instructions on moving from API v1 to API v2.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2"/>, <see cref="global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChatPostResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2? ChatResponseV2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2 ChatResponseV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2? StreamedChatResponseV2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2 StreamedChatResponseV2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Cohere.OpenApiClient.V2.Chat.ChatRequestBuilder.ChatPostResponse();
                if("ChatResponseV2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ChatResponseV2 = new global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.StreamedChatResponseV2 = new global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ChatResponseV2 != null)
                {
                    return ChatResponseV2.GetFieldDeserializers();
                }
                else if(StreamedChatResponseV2 != null)
                {
                    return StreamedChatResponseV2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ChatResponseV2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ChatResponseV2>(null, ChatResponseV2);
                }
                else if(StreamedChatResponseV2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.StreamedChatResponseV2>(null, StreamedChatResponseV2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
