// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Classify
{
    /// <summary>The type of classification performed</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClassifyPostResponse_classifications_classification_type
    {
        [EnumMember(Value = "single-label")]
        #pragma warning disable CS1591
        SingleLabel,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi-label")]
        #pragma warning disable CS1591
        MultiLabel,
        #pragma warning restore CS1591
    }
}
