// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Classify
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ClassifyPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of examples to provide context to the model. Each example is a text string and its associated label/class. Each unique label requires at least 2 examples associated with it; the maximum number of examples is 2500, and each example has a maximum length of 512 tokens. The values should be structured as `{text: &quot;...&quot;,label: &quot;...&quot;}`.Note: [Fine-tuned Models](https://docs.cohere.com/docs/classify-fine-tuning) trained on classification examples don&apos;t require the `examples` parameter to be passed in explicitly.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ClassifyExample>? Examples { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ClassifyExample> Examples { get; set; }
#endif
        /// <summary>A list of up to 96 texts to be classified. Each one must be a non-empty string.There is, however, no consistent, universal limit to the length a particular input can be. We perform classification on the first `x` tokens of each input, and `x` varies depending on which underlying model is powering classification. The maximum token length for each model is listed in the &quot;max tokens&quot; column [here](https://docs.cohere.com/docs/models).Note: by default the `truncate` parameter is set to `END`, so tokens exceeding the limit will be automatically dropped. This behavior can be disabled by setting `truncate` to `NONE`, which will result in validation errors for longer texts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Inputs { get; set; }
#nullable restore
#else
        public List<string> Inputs { get; set; }
#endif
        /// <summary>ID of a [Fine-tuned](https://docs.cohere.com/v2/docs/classify-starting-the-training) Classify model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The ID of a custom playground preset. You can create presets in the [playground](https://dashboard.cohere.com/playground). If you use a preset, all other parameters become optional, and any included parameters will override the preset&apos;s parameters.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Preset { get; set; }
#nullable restore
#else
        public string Preset { get; set; }
#endif
        /// <summary>One of `NONE|START|END` to specify how the API will handle inputs longer than the maximum token length.Passing `START` will discard the start of the input. `END` will discard the end of the input. In both cases, input is discarded until the remaining input is exactly the maximum input token length for the model.If `NONE` is selected, when the input exceeds the maximum input token length an error will be returned.</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody_truncate? Truncate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody"/> and sets the default values.
        /// </summary>
        public ClassifyPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Truncate = global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody_truncate.END;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "examples", n => { Examples = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ClassifyExample>(global::Soenneker.Cohere.OpenApiClient.Models.ClassifyExample.CreateFromDiscriminatorValue)?.AsList(); } },
                { "inputs", n => { Inputs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "preset", n => { Preset = n.GetStringValue(); } },
                { "truncate", n => { Truncate = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody_truncate>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ClassifyExample>("examples", Examples);
            writer.WriteCollectionOfPrimitiveValues<string>("inputs", Inputs);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("preset", Preset);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostRequestBody_truncate>("truncate", Truncate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
