// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Classify
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ClassifyPostResponse_classifications : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type of classification performed</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_classification_type? ClassificationType { get; set; }
        /// <summary>The confidence score for the top predicted class (only filled for single-label classification)</summary>
        [Obsolete("")]
        public float? Confidence { get; set; }
        /// <summary>An array containing the confidence scores of all the predictions in the same order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<float?>? Confidences { get; set; }
#nullable restore
#else
        public List<float?> Confidences { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The input text that was classified</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Input { get; set; }
#nullable restore
#else
        public string Input { get; set; }
#endif
        /// <summary>A map containing each label and its confidence score according to the classifier. All the confidence scores add up to 1 for single-label classification. For multi-label classification the label confidences are independent of each other, so they don&apos;t have to sum up to 1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_labels? Labels { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_labels Labels { get; set; }
#endif
        /// <summary>The predicted label for the associated query (only filled for single-label models)</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prediction { get; set; }
#nullable restore
#else
        public string Prediction { get; set; }
#endif
        /// <summary>An array containing the predicted labels for the associated query (only filled for single-label classification)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Predictions { get; set; }
#nullable restore
#else
        public List<string> Predictions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications"/> and sets the default values.
        /// </summary>
        public ClassifyPostResponse_classifications()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "classification_type", n => { ClassificationType = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_classification_type>(); } },
                { "confidence", n => { Confidence = n.GetFloatValue(); } },
                { "confidences", n => { Confidences = n.GetCollectionOfPrimitiveValues<float?>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input", n => { Input = n.GetStringValue(); } },
                { "labels", n => { Labels = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_labels>(global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_labels.CreateFromDiscriminatorValue); } },
                { "prediction", n => { Prediction = n.GetStringValue(); } },
                { "predictions", n => { Predictions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_classification_type>("classification_type", ClassificationType);
            writer.WriteFloatValue("confidence", Confidence);
            writer.WriteCollectionOfPrimitiveValues<float?>("confidences", Confidences);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("input", Input);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.V1.Classify.ClassifyPostResponse_classifications_labels>("labels", Labels);
            writer.WriteStringValue("prediction", Prediction);
            writer.WriteCollectionOfPrimitiveValues<string>("predictions", Predictions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
