// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.Models;
using Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.EmbedJobs
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\embed-jobs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmbedJobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Cohere.OpenApiClient.v1.embedJobs.item collection</summary>
        /// <param name="position">The ID of the embed job to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.EmbedJobsItemRequestBuilder"/></returns>
        public global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.EmbedJobsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.EmbedJobsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.EmbedJobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbedJobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/embed-jobs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.EmbedJobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbedJobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/embed-jobs", rawUrl)
        {
        }
        /// <summary>
        /// The list embed job endpoint allows users to view all embed jobs history for that specific user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse498Error">When receiving a 498 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse499Error">When receiving a 499 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse501Error">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse429Error.CreateFromDiscriminatorValue },
                { "498", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse498Error.CreateFromDiscriminatorValue },
                { "499", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse499Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse500Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse501Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse>(requestInfo, global::Soenneker.Cohere.OpenApiClient.Models.ListEmbedJobResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This API launches an async Embed job for a [Dataset](https://docs.cohere.com/docs/datasets) of type `embed-input`. The result of a completed embed job is new Dataset of type `embed-output`, which contains the original text entries and the corresponding embeddings.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse498Error">When receiving a 498 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse499Error">When receiving a 499 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse501Error">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse?> PostAsync(global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse> PostAsync(global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse429Error.CreateFromDiscriminatorValue },
                { "498", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse498Error.CreateFromDiscriminatorValue },
                { "499", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse499Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse500Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse501Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse>(requestInfo, global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The list embed job endpoint allows users to view all embed jobs history for that specific user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This API launches an async Embed job for a [Dataset](https://docs.cohere.com/docs/datasets) of type `embed-input`. The result of a completed embed job is new Dataset of type `embed-output`, which contains the original text entries and the corresponding embeddings.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Cohere.OpenApiClient.Models.CreateEmbedJobRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.EmbedJobsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.EmbedJobsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.EmbedJobsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
