// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\batches\{id}:cancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithIdCancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel.WithIdCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="id">The batch ID.</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIdCancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string id = "") : base(requestAdapter, "{+baseurl}/v2/batches/{id}:cancel", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(id)) PathParameters.Add("id", id);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel.WithIdCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithIdCancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/batches/{id}:cancel", rawUrl)
        {
        }
        /// <summary>
        /// Cancels an in-progress batch
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.Models.CancelBatchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.BatchError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.CancelBatchResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Cohere.OpenApiClient.Models.CancelBatchResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.BatchError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Cohere.OpenApiClient.Models.CancelBatchResponse>(requestInfo, global::Soenneker.Cohere.OpenApiClient.Models.CancelBatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Cancels an in-progress batch
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel.WithIdCancelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel.WithIdCancelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cohere.OpenApiClient.V2.Batches.WithIdCancel.WithIdCancelRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
