// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Chat
{
    /// <summary>Defaults to `&quot;enabled&quot;`.Citations are enabled by default for models that support it, but can be turned off by setting `&quot;type&quot;: &quot;disabled&quot;`.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatPostRequestBody_citation_quality
    {
        [EnumMember(Value = "ENABLED")]
        #pragma warning disable CS1591
        ENABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLED")]
        #pragma warning disable CS1591
        DISABLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAST")]
        #pragma warning disable CS1591
        FAST,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCURATE")]
        #pragma warning disable CS1591
        ACCURATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OFF")]
        #pragma warning disable CS1591
        OFF,
        #pragma warning restore CS1591
    }
}
