// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Chat
{
    /// <summary>Used to select the [safety instruction](https://docs.cohere.com/docs/safety-modes) inserted into the prompt. Defaults to `CONTEXTUAL`.When `NONE` is specified, the safety instruction will be omitted.Safety modes are not yet configurable in combination with `tools`, `tool_results` and `documents` parameters.**Note**: This parameter is only compatible newer Cohere models, starting with [Command R 08-2024](https://docs.cohere.com/docs/command-r#august-2024-release) and [Command R+ 08-2024](https://docs.cohere.com/docs/command-r-plus#august-2024-release).**Note**: `command-r7b-12-2024` and newer models only support `&quot;CONTEXTUAL&quot;` and `&quot;STRICT&quot;` modes.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatPostRequestBody_safety_mode
    {
        [EnumMember(Value = "CONTEXTUAL")]
        #pragma warning disable CS1591
        CONTEXTUAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRICT")]
        #pragma warning disable CS1591
        STRICT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
    }
}
