// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.Chat
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of previous messages between the user and the model, giving the model conversational context for responding to the user&apos;s `message`.Each item represents a single message in the chat history, excluding the current user turn. It has two properties: `role` and `message`. The `role` identifies the sender (`CHATBOT`, `SYSTEM`, or `USER`), while the `message` contains the text content.The chat_history parameter should not be used for `SYSTEM` messages in most cases. Instead, to add a `SYSTEM` role message at the beginning of a conversation, the `preamble` parameter should be used.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Message>? ChatHistory { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Message> ChatHistory { get; set; }
#endif
        /// <summary>Defaults to `&quot;enabled&quot;`.Citations are enabled by default for models that support it, but can be turned off by setting `&quot;type&quot;: &quot;disabled&quot;`.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_citation_quality? CitationQuality { get; set; }
        /// <summary>Accepts `{&quot;id&quot;: &quot;web-search&quot;}`, and/or the `&quot;id&quot;` for a custom [connector](https://docs.cohere.com/docs/connectors), if you&apos;ve [created](https://docs.cohere.com/v1/docs/creating-and-deploying-a-connector) one.When specified, the model&apos;s reply will be enriched with information found by querying each of the connectors (RAG).Compatible Deployments: Cohere Platform</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatConnector>? Connectors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatConnector> Connectors { get; set; }
#endif
        /// <summary>An alternative to `chat_history`.Providing a `conversation_id` creates or resumes a persisted conversation with the specified ID. The ID can be any non empty string.Compatible Deployments: Cohere Platform</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>A list of relevant documents that the model can cite to generate a more accurate reply. Each document is a string-string dictionary.Example:```[  { &quot;title&quot;: &quot;Tall penguins&quot;, &quot;text&quot;: &quot;Emperor penguins are the tallest.&quot; },  { &quot;title&quot;: &quot;Penguin habitats&quot;, &quot;text&quot;: &quot;Emperor penguins only live in Antarctica.&quot; },]```Keys and values from each document will be serialized to a string and passed to the model. The resulting generation will include citations that reference some of these documents.Some suggested keys are &quot;text&quot;, &quot;author&quot;, and &quot;date&quot;. For better generation quality, it is recommended to keep the total word count of the strings in the dictionary to under 300 words.An `id` field (string) can be optionally supplied to identify the document in the citations. This field will not be passed to the model.An `_excludes` field (array of strings) can be optionally supplied to omit some key-value pairs from being shown to the model. The omitted fields will still show up in the citation object. The &quot;_excludes&quot; field will not be passed to the model.See [&apos;Document Mode&apos;](https://docs.cohere.com/docs/retrieval-augmented-generation-rag#document-mode) in the guide for more information.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>? Documents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument> Documents { get; set; }
#endif
        /// <summary>Forces the chat to be single step. Defaults to `false`.</summary>
        public bool? ForceSingleStep { get; set; }
        /// <summary>Defaults to `0.0`, min value of `0.0`, max value of `1.0`.Used to reduce repetitiveness of generated tokens. The higher the value, the stronger a penalty is applied to previously present tokens, proportional to how many times they have already appeared in the prompt or prior generation.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public double? FrequencyPenalty { get; set; }
        /// <summary>Ensures only the top `k` most likely tokens are considered for generation at each step.Defaults to `0`, min value of `0`, max value of `500`.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public int? K { get; set; }
        /// <summary>The maximum number of input tokens to send to the model. If not specified, `max_input_tokens` is the model&apos;s context length limit minus a small buffer.Input will be truncated according to the `prompt_truncation` parameter.Compatible Deployments: Cohere Platform</summary>
        public int? MaxInputTokens { get; set; }
        /// <summary>The maximum number of tokens the model will generate as part of the response. Note: Setting a low value may result in incomplete generations.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public int? MaxTokens { get; set; }
        /// <summary>Text input for the model to respond to.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The name of a compatible [Cohere model](https://docs.cohere.com/docs/models) or the ID of a [fine-tuned](https://docs.cohere.com/docs/chat-fine-tuning) model.Compatible Deployments: Cohere Platform, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Ensures that only the most likely tokens, with total probability mass of `p`, are considered for generation at each step. If both `k` and `p` are enabled, `p` acts after `k`.Defaults to `0.75`. min value of `0.01`, max value of `0.99`.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public double? P { get; set; }
        /// <summary>When specified, the default Cohere preamble will be replaced with the provided one. Preambles are a part of the prompt used to adjust the model&apos;s overall behavior and conversation style, and use the `SYSTEM` role.The `SYSTEM` role is also used for the contents of the optional `chat_history=` parameter. When used with the `chat_history=` parameter it adds content throughout a conversation. Conversely, when used with the `preamble=` parameter it adds content at the start of the conversation only.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Preamble { get; set; }
#nullable restore
#else
        public string Preamble { get; set; }
#endif
        /// <summary>Defaults to `0.0`, min value of `0.0`, max value of `1.0`.Used to reduce repetitiveness of generated tokens. Similar to `frequency_penalty`, except that this penalty is applied equally to all tokens that have already appeared, regardless of their exact frequencies.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public double? PresencePenalty { get; set; }
        /// <summary>Defaults to `AUTO` when `connectors` are specified and `OFF` in all other cases.Dictates how the prompt will be constructed.With `prompt_truncation` set to &quot;AUTO&quot;, some elements from `chat_history` and `documents` will be dropped in an attempt to construct a prompt that fits within the model&apos;s context length limit. During this process the order of the documents and chat history will be changed and ranked by relevance.With `prompt_truncation` set to &quot;AUTO_PRESERVE_ORDER&quot;, some elements from `chat_history` and `documents` will be dropped in an attempt to construct a prompt that fits within the model&apos;s context length limit. During this process the order of the documents and chat history will be preserved as they are inputted into the API.With `prompt_truncation` set to &quot;OFF&quot;, no elements will be dropped. If the sum of the inputs exceeds the model&apos;s context length limit, a `TooManyTokens` error will be returned.Compatible Deployments: - AUTO: Cohere Platform Only - AUTO_PRESERVE_ORDER: Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_prompt_truncation? PromptTruncation { get; set; }
        /// <summary>When enabled, the user&apos;s prompt will be sent to the model withoutany pre-processing.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public bool? RawPrompting { get; set; }
        /// <summary>Configuration for forcing the model output to adhere to the specified format. Supported on [Command R 03-2024](https://docs.cohere.com/docs/command-r), [Command R+ 04-2024](https://docs.cohere.com/docs/command-r-plus) and newer models.The model can be forced into outputting JSON objects (with up to 5 levels of nesting) by setting `{ &quot;type&quot;: &quot;json_object&quot; }`.A [JSON Schema](https://json-schema.org/) can optionally be provided, to ensure a specific structure.**Note**: When using  `{ &quot;type&quot;: &quot;json_object&quot; }` your `message` should always explicitly instruct the model to generate a JSON (eg: _&quot;Generate a JSON ...&quot;_) . Otherwise the model may end up getting stuck generating an infinite stream of characters and eventually run out of context length.**Limitation**: The parameter is not supported in RAG mode (when any of `connectors`, `documents`, `tools`, `tool_results` are provided).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat? ResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat ResponseFormat { get; set; }
#endif
        /// <summary>Used to select the [safety instruction](https://docs.cohere.com/docs/safety-modes) inserted into the prompt. Defaults to `CONTEXTUAL`.When `NONE` is specified, the safety instruction will be omitted.Safety modes are not yet configurable in combination with `tools`, `tool_results` and `documents` parameters.**Note**: This parameter is only compatible newer Cohere models, starting with [Command R 08-2024](https://docs.cohere.com/docs/command-r#august-2024-release) and [Command R+ 08-2024](https://docs.cohere.com/docs/command-r-plus#august-2024-release).**Note**: `command-r7b-12-2024` and newer models only support `&quot;CONTEXTUAL&quot;` and `&quot;STRICT&quot;` modes.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_safety_mode? SafetyMode { get; set; }
        /// <summary>Defaults to `false`.When `true`, the response will only contain a list of generated search queries, but no search will take place, and no reply from the model to the user&apos;s `message` will be generated.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        [Obsolete("")]
        public bool? SearchQueriesOnly { get; set; }
        /// <summary>If specified, the backend will make a best effort to sample tokensdeterministically, such that repeated requests with the sameseed and parameters should return the same result. However,determinism cannot be totally guaranteed.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public int? Seed { get; set; }
        /// <summary>A list of up to 5 strings that the model will use to stop generation. If the model generates a string that matches any of the strings in the list, it will stop generating tokens and return the generated text up to that point not including the stop sequence.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StopSequences { get; set; }
#nullable restore
#else
        public List<string> StopSequences { get; set; }
#endif
        /// <summary>Defaults to `false`.When `true`, the response will be a JSON stream of events. The final event will contain the complete response, and will have an `event_type` of `&quot;stream-end&quot;`.Streaming is beneficial for user interfaces that render the contents of the response piece by piece, as it gets generated.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public bool? Stream { get; set; }
        /// <summary>Defaults to `0.3`.A non-negative float that tunes the degree of randomness in generation. Lower temperatures mean less random generations, and higher temperatures mean more random generations.Randomness can be further maximized by increasing the  value of the `p` parameter.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
        public float? Temperature { get; set; }
        /// <summary>A list of results from invoking tools recommended by the model in the previous chat turn. Results are used to produce a text response and will be referenced in citations. When using `tool_results`, `tools` must be passed as well.Each tool_result contains information about how it was invoked, as well as a list of outputs in the form of dictionaries.**Note**: `outputs` must be a list of objects. If your tool returns a single object (eg `{&quot;status&quot;: 200}`), make sure to wrap it in a list.```tool_results = [  {    &quot;call&quot;: {      &quot;name&quot;: &lt;tool name&gt;,      &quot;parameters&quot;: {        &lt;param name&gt;: &lt;param value&gt;      }    },    &quot;outputs&quot;: [{      &lt;key&gt;: &lt;value&gt;    }]  },  ...]```**Note**: Chat calls with `tool_results` should not be included in the Chat history to avoid duplication of the message text.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolResult>? ToolResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.ToolResult> ToolResults { get; set; }
#endif
        /// <summary>A list of available tools (functions) that the model may suggest invoking before producing a text response.When `tools` is passed (without `tool_results`), the `text` field in the response will be `&quot;&quot;` and the `tool_calls` field in the response will be populated with a list of tool calls that need to be made. If no calls need to be made, the `tool_calls` array will be empty.Compatible Deployments: Cohere Platform, Azure, AWS Sagemaker/Bedrock, Private Deployments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Tool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cohere.OpenApiClient.Models.Tool> Tools { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody"/> and sets the default values.
        /// </summary>
        public ChatPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chat_history", n => { ChatHistory = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Message>(global::Soenneker.Cohere.OpenApiClient.Models.Message.CreateFromDiscriminatorValue)?.AsList(); } },
                { "citation_quality", n => { CitationQuality = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_citation_quality>(); } },
                { "connectors", n => { Connectors = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatConnector>(global::Soenneker.Cohere.OpenApiClient.Models.ChatConnector.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conversation_id", n => { ConversationId = n.GetStringValue(); } },
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>(global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument.CreateFromDiscriminatorValue)?.AsList(); } },
                { "force_single_step", n => { ForceSingleStep = n.GetBoolValue(); } },
                { "frequency_penalty", n => { FrequencyPenalty = n.GetDoubleValue(); } },
                { "k", n => { K = n.GetIntValue(); } },
                { "max_input_tokens", n => { MaxInputTokens = n.GetIntValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "p", n => { P = n.GetDoubleValue(); } },
                { "preamble", n => { Preamble = n.GetStringValue(); } },
                { "presence_penalty", n => { PresencePenalty = n.GetDoubleValue(); } },
                { "prompt_truncation", n => { PromptTruncation = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_prompt_truncation>(); } },
                { "raw_prompting", n => { RawPrompting = n.GetBoolValue(); } },
                { "response_format", n => { ResponseFormat = n.GetObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat>(global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat.CreateFromDiscriminatorValue); } },
                { "safety_mode", n => { SafetyMode = n.GetEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_safety_mode>(); } },
                { "search_queries_only", n => { SearchQueriesOnly = n.GetBoolValue(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "stop_sequences", n => { StopSequences = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "temperature", n => { Temperature = n.GetFloatValue(); } },
                { "tool_results", n => { ToolResults = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolResult>(global::Soenneker.Cohere.OpenApiClient.Models.ToolResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Tool>(global::Soenneker.Cohere.OpenApiClient.Models.Tool.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Message>("chat_history", ChatHistory);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_citation_quality>("citation_quality", CitationQuality);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatConnector>("connectors", Connectors);
            writer.WriteStringValue("conversation_id", ConversationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ChatDocument>("documents", Documents);
            writer.WriteBoolValue("force_single_step", ForceSingleStep);
            writer.WriteDoubleValue("frequency_penalty", FrequencyPenalty);
            writer.WriteIntValue("k", K);
            writer.WriteIntValue("max_input_tokens", MaxInputTokens);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("model", Model);
            writer.WriteDoubleValue("p", P);
            writer.WriteStringValue("preamble", Preamble);
            writer.WriteDoubleValue("presence_penalty", PresencePenalty);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_prompt_truncation>("prompt_truncation", PromptTruncation);
            writer.WriteBoolValue("raw_prompting", RawPrompting);
            writer.WriteObjectValue<global::Soenneker.Cohere.OpenApiClient.Models.ResponseFormat>("response_format", ResponseFormat);
            writer.WriteEnumValue<global::Soenneker.Cohere.OpenApiClient.V1.Chat.ChatPostRequestBody_safety_mode>("safety_mode", SafetyMode);
            writer.WriteBoolValue("search_queries_only", SearchQueriesOnly);
            writer.WriteIntValue("seed", Seed);
            writer.WriteCollectionOfPrimitiveValues<string>("stop_sequences", StopSequences);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteFloatValue("temperature", Temperature);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.ToolResult>("tool_results", ToolResults);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cohere.OpenApiClient.Models.Tool>("tools", Tools);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
