// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cohere.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\embed-jobs\{id}\cancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/embed-jobs/{id}/cancel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/embed-jobs/{id}/cancel", rawUrl)
        {
        }
        /// <summary>
        /// This API allows users to cancel an active embed job. Once invoked, the embedding process will be terminated, and users will be charged for the embeddings processed up to the cancellation point. It&apos;s important to note that partial results will not be available to users after cancellation.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel498Error">When receiving a 498 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel499Error">When receiving a 499 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel501Error">When receiving a 501 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.Cohere.OpenApiClient.Models.Cancel504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Cohere.OpenApiClient.Models.Cancel400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Cohere.OpenApiClient.Models.Cancel401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Cohere.OpenApiClient.Models.Cancel403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Cohere.OpenApiClient.Models.Cancel404Error.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Cohere.OpenApiClient.Models.Cancel422Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Cohere.OpenApiClient.Models.Cancel429Error.CreateFromDiscriminatorValue },
                { "498", global::Soenneker.Cohere.OpenApiClient.Models.Cancel498Error.CreateFromDiscriminatorValue },
                { "499", global::Soenneker.Cohere.OpenApiClient.Models.Cancel499Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Cohere.OpenApiClient.Models.Cancel500Error.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Cohere.OpenApiClient.Models.Cancel501Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Cohere.OpenApiClient.Models.Cancel503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Cohere.OpenApiClient.Models.Cancel504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This API allows users to cancel an active embed job. Once invoked, the embedding process will be terminated, and users will be charged for the embeddings processed up to the cancellation point. It&apos;s important to note that partial results will not be available to users after cancellation.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel.CancelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel.CancelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Cohere.OpenApiClient.V1.EmbedJobs.Item.Cancel.CancelRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
